[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200
upload_speed = 921600 

; Puerto: Asegúrate de que siga siendo el COM23 o cámbialo si lo moviste de USB
monitor_port = COM9
upload_port = COM9

board_build.filesystem = littlefs 

build_flags = 
    -D MQTT_MAX_PACKET_SIZE=1024  ; <--- Aumentado un poco por si mandas muchos datos del buffer rápido
    -D CORE_DEBUG_LEVEL=0

lib_deps = 
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.18.5
    https://github.com/io7lab/IO7F32.git